apiVersion: v1
kind: Secret
metadata:
  name: translator-secrets
  namespace: translator
type: Opaque
stringData:
  # Dodajemy ?search_path=public, aby wymusić na backendzie patrzenie w dobre miejsce
  DATABASE_URL: "postgresql://app:secret@postgres:5432/translator?search_path=public"
  REDIS_URL: "redis://redis:6379"
